name: CI

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:

jobs:

  ci:
    name: Build and test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare local toolchain
        run: |
          rustup component add clippy
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Check for changes
        run: git diff --exit-code

      - name: Format
        run: cargo fmt -- --check

      - name: Check
        run: cargo check

      - name: Lint
        run: cargo clippy -- -D warnings

      - name: Test
        run: cargo test --all

      - name: Build
        run: cargo build --release

  release:
    uses: proton-decay/ghtest/.github/workflows/tag-rust.yml@main
    inputs:
      gh_token:: ${{ secrets.GITHUB_TOKEN }}
