name: CI

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:

jobs:

  ci:
    name: Build and test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          cargo install cargo-typify

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version
          cargo typify --version

      - name: Regenerate models
        run: ./scripts/generate.sh

      - name: Check for changes
        run: git diff --exit-code

      - name: Format
        run: cargo fmt -- --check

      - name: Check
        run: cargo check

      - name: Lint
        run: cargo clippy -- -D warnings

      - name: Test
        run: cargo test --all

      - name: Build
        run: cargo build --release

  tag:
    name: Tag the release
    needs: ci
    runs-on: ubuntu-latest

    if: ${{ github.ref == 'main' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update local toolchain
        run: |
          rustup update
          cargo install cargo-get

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo get --version

      - name: Get versions
        id: versions
        run: |
          echo "prev=`git describe --tags --abbrev=0`" >> "$GITHUB_OUTPUT"
          echo "next=`cargo get workspace.package.version`" >> "$GITHUB_OUTPUT"

      - name: Create tag
        if: ${{ step.versions.output.prev == format('v{0}', step.versions.output.next) }}
        run: gh release create v${{ step.versions.output.next }} --notes "Release ${{ step.versions.output.next }}"
