name: Tag if version bumped (Dart)

on:
  workflow_call:
    inputs:
      pubspec_path:
        required: false
        type: string
    secrets:
      gh_token:
        required: true

jobs:

  tag-dart:
    name: Tag if version bumped
    runs-on: ubuntu-latest
    
    # Pushed or merged to `main`
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Get versions
        id: versions
        run: |
          prev="$(git describe --tags --abbrev=0)"
          next="v$(yq eval '.version' ${{ inputs.pubspec_path }})"
          echo "Versions: prev='$prev', next='$next'"
          if [[ -z "$prev" ]] || [[ -z "$next" ]] then
            echo "Failed to get the versions"
            exit 1
          fi
          echo "prev=$prev" >> "$GITHUB_OUTPUT"
          echo "next=$next" >> "$GITHUB_OUTPUT"

      - name: Create tag if version bumped
        if: steps.versions.outputs.prev != steps.versions.outputs.next
        env:
          GH_TOKEN: ${{ secrets.gh_token }}
        run: |
          gh release create ${{ steps.versions.outputs.next }} \
              --notes "Release ${{ steps.versions.outputs.next }}"
